---
title: "Figure Quadrant (lab analysis)"
author: "Mercè Garí"
output:
  html_document:
    df_print: paged
    dev: png
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

Compilation date: `r format(Sys.time(), '%d.%m.%Y')`

# Prepare

```{r}
here_r = function (...) here::here("Statistics", "R", ...)
here_lab_data = function (...) here::here("Lab_paper2_data", ...)
here_out = function (...) here::here("Lab_paper2_output", "figure_quadrant", ...)

dir.create(here_out(), showWarnings = FALSE)

library(magrittr)
library(ggplot2)

# Load settings
source(here_r("setup.R"))
source(here_r("functions.R"))

library(dplyr)
source(here_r("RainCloudPlots", "R_rainclouds.R")) 


# Load data
#  Single data contains only one blood sample per participant
single_data = read.csv(here_lab_data(
  "Global_Data", "wide_plot_merce.csv"), stringsAsFactors = F)

# # Assertions
# if (length(unique(single_data$blut_ID)) != nrow(single_data)) {stop("Blood id not unique")}
# if (length(unique(single_data$tln_ID)) != nrow(single_data)) {stop("Participant id not unique")}

###############################################################################
# Clean data

data = single_data

# #  Unique labels
# data[data=="Positiv" | data=="pos." | data=="reactive" | 
#        data=="positive"] = "Positive"
# data[data=="Negativ" | data=="Indeterminate" | 
#        data=="neg." | data=="ind." | 
#        data=="nonreactive" | data=="negative" | 
#        data=="not_reactive"] = "Negative"

# #  Remove Roche 0 values
# val_cols = grep("roche_COI", colnames(data), value=T)
# res_cols = grep("roche_Interpretation", colnames(data), value=T)
# cat("# Roche == 0 before removal:", sum(data[,val_cols]==0, na.rm=T), "\n")
# 
# for (j in 1:length(val_cols)) {
#   # Conveniently, the order is the same
#   val_col = val_cols[[j]]
#   res_col = res_cols[[j]]
#   data[data[,val_col]==0 & !is.na(data[,val_col]), res_col] = NA
#   data[data[,val_col]==0 & !is.na(data[,val_col]), val_col] = NA
# }

#  Add binary ground truth column
data['Ground truth'] = ifelse(is.na(data$model_outcome), "Unknown", 
                              ifelse(data$model_outcome=="true_positive",
                                     "True-positive",
                                     "True-negative"))
data$`Ground truth` = factor(as.character(data$`Ground truth`),
                             levels = c("Unknown", "True-negative", 
                                        "True-positive"))

# #  NT to categories with correct ordering
# data$NT = factor(as.character(data$NT), 
#                  levels = c("<10", "10", "20", "40", ">80"))
# 
# # TODO currently is 4.75, which is bad when setting manually <10 -> 5
# cutoff$new$NT = 10

###############################################################################
# Check data consistency

#' Check consistency of reported values according to assumed thresholds
# check_consistency = function(val_cols, res_cols, threshold) {
#   for (j in 1:length(val_cols)) {
#     # Assuming that value and result columns have the same order
#     val_col = val_cols[[j]]
#     res_col = res_cols[[j]]
#     by_value = sum(data[,val_col]>=threshold, na.rm=T)
#     by_cat = sum(data[,res_col] == "Positive", na.rm=T)
#     if (by_value != by_cat) { stop(paste("Mismatch positives (exp./act.)", by_value, by_cat)) }
#     by_value = sum(data[,val_col]<threshold, na.rm=T)
#     by_cat = sum(data[,res_col] == "Negative", na.rm=T)
#     if (by_value != by_cat) { stop(paste("Mismatch negatives (exp./act.)", by_value, by_cat)) }
#   }
# }
# 
#  Roche
# val_cols = grep("roche_COI", colnames(data), value=T)
# res_cols = grep("roche_Interpretation", colnames(data), value=T)
# check_consistency(val_cols, res_cols, 1.0)
# if (any(data[,val_cols]==0, na.rm=T)) {stop("There are Roche zero values.")}
# 
# #  Euroimmun
# val_cols = grep("eur_quotient", colnames(data), value=T)
# res_cols = grep("eur_der_test_result", colnames(data), value=T)
# check_consistency(val_cols, res_cols, 1.1)
# if (any(data[,val_cols]==0, na.rm=T)) {stop("There are Euroimmun zero values.")}

# Use corrected data frame
#single_data = data

# Tidy up
#rm(data, val_cols, res_cols, val_col, res_col, j)

#' Create a plot with the `title` string above the `plt` plot row.
title_plot = function(title, plt, plot.margin=margin(0,0,0,7), rel_heights=c(0.1,1)) {
  plot_grid(
    ggdraw() + draw_label(title, fontface='bold', x=0, hjust=0) + theme(plot.margin = plot.margin),
    plt, ncol=1, rel_heights=rel_heights
  )
}

```

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggpmisc)
library(stringr)
library(GGally)
library(cowplot)
library(forcats)

lab <- data %>%
  as_tibble() %>%
  select(-X, -model_outcome) %>%
  spread(tests_all, values) %>%
  rename(IgA = Eur_IgA, IgG = Eur_IgG)

lab.array <- lab %>%
  select(id, pers_id, 
         VC_S1_IgA, VC_S2_IgA, VC_N_IgA,
         VC_S1_IgG, VC_S2_IgG, VC_N_IgG,
         VC_S1_IgM, VC_S2_IgM, VC_N_IgM) %>%
  gather(array, value, -c(id, pers_id)) %>%
    mutate(value = ifelse(value == "<10", "5", value),
           value = as.numeric(value)) %>%
  spread(array, value)

lab <- lab %>%
  select(-c(VC_S1_IgA, VC_S2_IgA, VC_N_IgA,
         VC_S1_IgG, VC_S2_IgG, VC_N_IgG,
         VC_S1_IgM, VC_S2_IgM, VC_N_IgM)) %>%
  left_join(lab.array)


lab.lineblot <- lab %>%
  select(id, pers_id,
         LineBlot_NP_SARS_2, LineBlot_RBD_SARS_2,
         LineBlot_S1_SARS_2, 
         Schnupfen_NP_229E, Schnupfen_NP_NL63, 
         Schnupfen_NP_OC43, Schnupfen_NP_HKU1) %>%
  gather(lineblot, value, -c(id, pers_id)) %>%
  mutate(value = ifelse(value == "not_reactive", "0.5", value),
         value = as.numeric(value)) %>%
  spread(lineblot, value)

lab <- lab %>%
  select(-c(LineBlot_NP_SARS_2, LineBlot_RBD_SARS_2,
         LineBlot_S1_SARS_2,
         Schnupfen_NP_229E, Schnupfen_NP_NL63, 
         Schnupfen_NP_OC43, Schnupfen_NP_HKU1)) %>%
  left_join(lab.lineblot)


# Thresholds
thr.man <- as.data.frame(cutoff$old) %>%
  gather(Test, Manufacturer)
thr.cal <- as.data.frame(cutoff$new) %>%
  gather(Test, Optimized)
thresholds <- left_join(thr.man, thr.cal) %>%
  mutate(Test = ifelse(Test == "Eur_IgA", "IgA",
                       ifelse(Test == "Eur_IgG", "IgG", Test))) %>%
  as_tibble()
thresholds <- as.data.frame(thresholds)
# Add manually the Common cold thresholds (1 for all)
thresholds.additional <- data.frame(Test = c("Schnupfen_NP_229E",
                                             "Schnupfen_NP_NL63",
                                             "Schnupfen_NP_OC43",
                                             "Schnupfen_NP_HKU1"),
                                    Manufacturer = rep(1, 4),
                                    Optimized = rep(1, 4))
                                      
thresholds <- rbind(thresholds, thresholds.additional)
thresholds$Manufacturer[thresholds$Test == "NT"] <- 10
str(thresholds)

thresholds <- thresholds %>%
  bind_rows(filter(thresholds, Test == "Roche") %>%
              mutate(Test = "Roche_S1"))
thresholds

lab.long <- lab %>%
  tidyr::gather(Test, value, 
                c(Roche_S1, Roche, IgG, IgA, cPass, 
                  VC_S1_IgA, VC_S2_IgA,  
                  VC_N_IgA, VC_S1_IgM, 
                  VC_S2_IgM, VC_N_IgM, 
                  VC_S1_IgG, VC_S2_IgG, 
                  VC_N_IgG, LineBlot_NP_SARS_2,
                  LineBlot_RBD_SARS_2, LineBlot_S1_SARS_2,
                  Schnupfen_NP_229E, Schnupfen_NP_NL63, 
         Schnupfen_NP_OC43, Schnupfen_NP_HKU1)) %>%
  select(id, pers_id, Test, value, `Ground truth`) %>%
  mutate(value = as.numeric(value))


  
Test.names <- data.frame(Test = unique(lab.long$Test),
                         name = c("Ro-S1", "Ro-N-Ig", "EI-S1-IgG", "EI-S1-IgA",
                                  "GS-cPass", 
                                  "VC S1 IgA", "VC S2 IgA", "VC N IgA",
                                  "VC S1 IgM", "VC S2 IgM", "VC N IgM",
                                  "VC S1 IgG", "VC S2 IgG", "VC N IgG",
                                  "MG-N", "MG-RBD", "MG-S1", 
                                  "NP-229E", "NP NL63", "NP-OC43", "NP-HKU1"))

Test.names


```


# Plot

```{r, fig.width = 10, fig.height = 6, results = FALSE, echo=FALSE, warning=FALSE}



############# Both optimized and manufacturer together
lab.long <- lab.long %>%
  left_join(Test.names) %>%
  select(-Test) %>%
  rename(Test = name)
thresholds <- thresholds %>%
  left_join(Test.names) %>%
  select(-Test) %>%
  rename(Test = name)

v <- 1
#for(v in 1:length(unique(lab.long.wo$Test))){
  v.now <- unique(lab.long$Test)[v]
  # Deal with counts at each quadrant
  no.se.que <- lab.long %>% 
    left_join(gather(thresholds, Type, Threshold, -Test)) %>%
    mutate(Position = ifelse(value >= Threshold, "Above", "Below")) %>%
    select(-value, -Threshold) %>% 
    spread(Test, Position) %>%
    gather(Test, Position, -c(id, pers_id,
                           `Ground truth`, Type, v.now)) %>%
    filter(Test != v.now) %>%
    filter(!is.na(Position)) %>%
    filter(!is.na(!!rlang::sym(v.now)))
  
  # Calculate total N for quadrant, test and ground truth
  counts.gt.quadrants <- no.se.que %>%
    group_by_at(c("Type", "Test", "Position", "Ground truth", v.now)) %>%
    summarize(N=n()) %>%
    ungroup()
  # Calculate N for ground truth
  counts.quadrants <- no.se.que %>%
    group_by_at(c("Type", "Test", "Ground truth")) %>%
    summarize(N.gt=n())  %>%
    ungroup()
  # Calculate percentage, combining the both above
  counts <- left_join(counts.gt.quadrants, counts.quadrants) %>%
    mutate(Percentage = N / N.gt * 100) %>%
    mutate(!!v.now := factor(!!rlang::sym(v.now), 
                             levels=c("Below", "Above")))
  # Here I select the Manufacturer cutoff
 counts <- counts %>%
  # filter(Type %in% "Manufacturer") %>%
   rename(Position.main = !!rlang::sym(v.now))
 
 counts <- counts %>%
   group_by(Type) %>%
   mutate(quadrant = case_when(
     Position == "Above" & Position.main == "Above" ~ 1,
     Position == "Above" & Position.main == "Below" ~ 2,
     Position == "Below" & Position.main == "Below" ~ 3,
     Position == "Below" & Position.main == "Above" ~ 4))
 counts <- counts %>%
   select(-Position, -Position.main)

 full.quadrants <- expand.grid(quadrant = 1:4,
        `Ground truth` = levels(counts$`Ground truth`),
        Test = unique(counts$Test),
        Type = unique(counts$Type))
 
 counts <- filter(counts, Test != v.now) %>%
  droplevels() %>%
   full_join(full.quadrants) %>%
   mutate(Percentage = ifelse(is.na(Percentage), 0, Percentage)) %>%
   ungroup()
 
 counts.man <- counts %>%
   filter(Type %in% "Manufacturer") %>%
   select(Test, `Ground truth`, Percentage, quadrant) %>%
   rename(Percentage.man = Percentage)
 counts.opt <- counts %>%
   filter(Type %in% "Optimized") %>%
   select(Test, `Ground truth`, Percentage, quadrant) %>%
   rename(Percentage.opt = Percentage)
 
 counts.now <- left_join(counts.man, counts.opt) %>%
   mutate(Percentage.man = paste0(as.character(round(Percentage.man, 0)), "%"),
          Percentage.opt = paste0(as.character(round(Percentage.opt, 0)), "%")) %>%
   mutate(Percentage = paste0(Percentage.man, " (", Percentage.opt, ")"))
 
 thresholds.now <- thresholds %>%
     filter(Test != "NT") 
  # End dealing with counts in each quadrant
  # Start plot
  plots.round <- lab.long %>% 
    spread(Test, value) %>%
    gather(Test, value, -c(id, pers_id,
                           `Ground truth`, v.now)) %>%
    filter(Test != v.now) %>%
    droplevels() %>%
    ggplot(aes(y = value, x = !!rlang::sym(v.now), 
                    color = `Ground truth`)) +
  geom_point(data = .%>% filter(`Ground truth` == "Unknown"), alpha=0.5) +
  geom_point(data = .%>% filter(`Ground truth` != "Unknown"), alpha=0.5) +
  scale_y_log10(expand=expansion(mult=c(0.3,0.3))) + 
  scale_x_log10(expand=expansion(mult=c(0.3,0.3))) +
  facet_wrap(~Test, scales="free", ncol=5) +
  theme_bw() +
   scale_colour_manual(values=style$pal3[c(2, 3, 1)]) +
  geom_hline(data = filter(thresholds.now, Test != v.now), 
             aes(yintercept=Manufacturer, lty=style$thr_lb_old),
             color=style$thr_lc_old) +
  geom_hline(data = filter(thresholds.now, Test != v.now), 
             aes(yintercept=Optimized, lty=style$thr_lb_new),
             color=style$thr_lc_new)  +
  geom_vline(xintercept = thresholds$Manufacturer[thresholds$Test == v.now],
             color=style$thr_lc_old, lty=style$thr_lt_old) +
  geom_vline(xintercept = thresholds$Optimized[thresholds$Test == v.now],
             color=style$thr_lc_new, lty=style$thr_lt_new) +
  scale_linetype_manual(name="Threshold",
                        values=c(style$thr_lt_old, style$thr_lt_new)) +
  ylab("Test value") + xlab(v.now) +
    ggtitle(v.now) +
    geom_text(data = filter(counts.now, quadrant == 1 & 
                              `Ground truth` == "True-positive"),
            aes(x=Inf, y=Inf, label=Percentage),
            hjust=1, vjust=1, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 1 & 
                              `Ground truth` == "True-negative"),
            aes(x=Inf, y=Inf, label=Percentage), 
            hjust=1, vjust=2.15, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 2 & 
                              `Ground truth` == "True-positive"),
            aes(x=0, y=Inf, label=Percentage),
            hjust=-0.1, vjust=1, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 2 & 
                              `Ground truth` == "True-negative"),
            aes(x=0, y=Inf, label=Percentage), 
            hjust=-0.1, vjust=2.3, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 3 & 
                              `Ground truth` == "True-positive"),
            aes(x=0, y=0, label=Percentage),
            hjust=-0.1, vjust=-0.1, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 3 & 
                              `Ground truth` == "True-negative"),
            aes(x=0, y=0, label=Percentage), 
            hjust=-0.1, vjust=-1.3, show.legend=FALSE, size=3.5) +
       geom_text(data = filter(counts.now, quadrant == 4 & 
                              `Ground truth` == "True-positive"),
            aes(x=Inf, y=0, label=Percentage),
            hjust=1, vjust=-0.1, show.legend=FALSE, size=3.5) +
    geom_text(data = filter(counts.now, quadrant == 4 & 
                              `Ground truth` == "True-negative"),
            aes(x=Inf, y=0, label=Percentage), 
            hjust=1, vjust=-1.3, show.legend=FALSE, size=3.5)
  plots.round  
  ggsave(here_out("plot-new-roche-measurement.pdf"), width=15, height=8)
  

```

